# Generated by Django 4.1 on 2022-08-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='subject',
        ),
    ]
