# Generated by Django 4.1 on 2022-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_signin_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
                ('message', models.TextField()),
            ],
        ),
    ]
